/*
 * Copyright (c) 2013 Mike Deats
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 * 
 * Created on May 4, 2013
 */

package critters.gui;

import java.util.ArrayList;
import java.util.HashMap;

import critters.Critter;
import critters.CritterModel;

/**
 *
 * @author  mike
 */
public class StatusPanel extends javax.swing.JPanel {
    
    private ArrayList<CritterState> critters;
    /** Creates new form StatusPanel */
    public StatusPanel() {
        initComponents();
        critters = new ArrayList<CritterState>();
    }
    
    
    public void addCritter(Class<? extends Critter>critterType, int population, int totalPopulation)
    {
        CritterState cs = new CritterState(critterType, population, totalPopulation);
        critters.add(cs);          
        add(cs);
    }
    
    public void clear()
    {
    	critters.clear();
    	removeAll();
    }
    
    public void update(CritterModel theModel)
    {
        for(CritterState cs : critters)
        {
            int pop = theModel.getPopulationCounters().get(cs.getType()).intValue();
            cs.update(pop, theModel.getPopulation());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setInheritsPopupMenu(true);
        setLayout(new java.awt.GridLayout(5, 4, 5, 5));
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
